### ISSUE TITLE
suspend cpu mining even if you can't log into your boid.com account

### ISSUE THREAD

**Issue by ghobson2013** [boid-com/BoidDesktop#4]
Hi , 

I noticed that users are unable to suspend their CPU mining, when boid.com is down for maintenance. There should really be no need to log into boid.com just to suspend mining activity.  I suggest we add on the GUI some kind of emergency suspend button.

**Comment by ghobson2013** [comment]
Workaround for now is:

open a command shell
then navigate to c:\Users\yourusername \ .Boid\BOINC
type the following once in that directory
boinccmd.exe --project  http://www.worldcommunitygrid.org/ suspend
that suspended the cpu mining for me

**Comment by boid-com** [comment]
The issue is that the GUI Widget would only render if it got a valid response from the server. I changed this so that if it received an invalid response it will ignore it. This means the GUI should remain visible and usable during network outages. Let me know if you find some case where the issue is not resolved.
